services:
  db:
    image: jithin56/library:database
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    volumes:
      - db_data:/var/lib/mysql

  auth_service:
    image: jithin56/library:auth
    deploy:
      replicas: 1
    ports:
      - "5001:5001"
    depends_on:
      - db  
    networks:
      - mynetwork

  book_service:
    image: jithin56/library:book
    deploy:
      replicas: 1
    ports:
      - "5002:5002"
    depends_on:
      - db
    networks:
      - mynetwork

  borrow_service:
    image: jithin56/library:borrow
    deploy:
      replicas: 1
    ports:
      - "5003:5003"
    depends_on:
      - db
    networks:
      - mynetwork

  frontend:
    image: jithin56/library:frontend
    deploy:
      replicas: 1
    ports:
      - "5000:5000"
    depends_on:
      - auth_service
      - book_service
      - borrow_service
    networks:
      - mynetwork

networks: 
  mynetwork:  
    driver: overlay

volumes:
  db_data:
